spring:
  datasource:
    url:
    # jdbc:mysql://localhost:3306/running_rank_dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update  # (create, update, validate 등)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
