spring:
  cache:
    cache-names:
      - top100RankingsCache
      - allUniversitiesCache
      - majorsByUniversityCache
#    caffeine:
#      spec: "maximumSize=100,expireAfterAccess=1m,refreshAfterWrite=30s"

  datasource:
    url: jdbc:mysql://localhost:3306/running_rank_dev

    # jdbc:mysql://localhost:3306/running_rank_dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update	  # (create, update, validate 등)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: hellosj20000612
    password: ddsjrfstemagwqox
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: dev-secret-key-2025-running-rank-hahaha
  access-token-expiration: 3600000      # 1시간 (밀리초)
  refresh-token-expiration: 1209600000  # 2주 (밀리초)

logging:
  level:
    root: info
    com.runningRank: debug

kakao:
  client-id: 30fd97fda368d489fb9ab92080ab4b3d
  redirect-uri: http://localhost:3000/oauth/callback/kakao

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: univ-marathon-rank
    sqs:
      ocr-queue-url: https://sqs.ap-northeast-2.amazonaws.com/992382358951/univ-marathon-ocr-processing-queue
      gpt-queue-url: https://sqs.ap-northeast-2.amazonaws.com/992382358951/univ-mararthon-gpt-processing-queue