spring:
  batch:
    jdbc:
      initialize-schema: always   # 초기 실행 시 메타테이블 자동 생성
    job:
      enabled: false   # 애플리케이션 실행 시 자동으로 Job 실행 안 하도록
  cache:
    cache-names:
      - top100RankingsCache
      - allUniversitiesCache
      - majorsByUniversityCache
#    caffeine:
#      spec: "maximumSize=100,expireAfterAccess=1m,refreshAfterWrite=30s"

  datasource:
    url: jdbc:mysql://localhost:3306/running_rank_dev

    # jdbc:mysql://localhost:3306/running_rank_dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update	  # (create, update, validate 등)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: hellosj20000612
    password: ddsjrfstemagwqox
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: dev-secret-key-2025-running-rank-hahaha
  access-token-expiration: 3600000      # 1시간 (밀리초)
  refresh-token-expiration: 1209600000  # 2주 (밀리초)

logging:
  level:
#    root: DEBUG
    org.springframework.cache: TRACE


kakao:
  client-id: 30fd97fda368d489fb9ab92080ab4b3d
  redirect-uri: http://localhost:3000/oauth/callback/kakao

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: univ-marathon-rank
    sqs:
      ocr-queue-url: https://sqs.ap-northeast-2.amazonaws.com/992382358951/univ-marathon-ocr-processing-queue
      gpt-queue-url: https://sqs.ap-northeast-2.amazonaws.com/992382358951/univ-mararthon-gpt-processing-queue
      mileage-queue-url: https://sqs.ap-northeast-2.amazonaws.com/992382358951/univ-marathon-get-user-mileage-queue

strava:
  client-id: 169874
  client-secret: d3165980b6d582391268524a560b60649ca19c09
#  redirect-uri: http://localhost:8080/api/auth/strava/callback
  redirect-uri: https://univ-marathon-server.p-e.kr/api/auth/strava/callback
  state-secret-key: your-very-long-and-secure-secret-key-for-strava-state-jwt # 아무 문자열이나 넣지 말고, 길고 복잡하며 외부에 노출되지 않아야 합니다. (최소 32바이트 이상 권장)
  state-expiration-millis: 300000 # state 토큰 유효 시간 (5분 = 300초 = 300000밀리초). 짧게 설정하는 것이 보안에 좋습니다.