name: CI - Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: 빌드
        run: ./gradlew clean build -x test -Dspring.profiles.active=prod

      - name: S3에 업로드
        run: |
          aws s3 cp build/libs/runningRank-0.0.1-SNAPSHOT.jar  s3://univ-marathon-rank/builds/app.jar --region ap-northeast-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: EC2 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 2. S3에서 새로운 JAR 파일 다운로드
            aws s3 cp s3://univ-marathon-rank/builds/app.jar ~/app.jar --region ap-northeast-2
            
            # 3. systemd 데몬 재로드 (서비스 파일 변경이 없다면 꼭 필요하진 않지만, 안전을 위해 실행)
            sudo systemctl daemon-reload
            
            # 4. 서비스 재시작
            # 기존에 stop 했으므로 start를 해도 되고, restart 명령어가 더 일반적입니다.
            sudo systemctl restart univ-marathon-rank
            # 또는 sudo systemctl restart univ-marathon-rank (더 권장)
            
            # 5. 서버 재부팅 시 자동 시작 설정 (이미 되어있다면 매번 실행할 필요는 없지만, 안전을 위해 유지 가능)
            sudo systemctl enable univ-marathon-rank
            
            # 6. 서비스 상태 확인
            sudo systemctl status univ-marathon-rank --no-pager
